path: # all will be extended by experiment name
  ckpt_path: "./output/ckpt"
  log_path: "./output/log"
  result_path: "./output/result"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 1.0e-09
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [30000, 40000, 50000]
  anneal_rate: 0.3
step:
  total_step: 40000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 10000
